/// <reference types="nativewind/types" />
/// <reference types="expo/types" />

// expo-env.d.ts is meant to be auto-generated by the Expo CLI, but in this project
// NativeWind's own tsconfig rewrite (triggered on every `expo start`) reliably drops
// both the file and its tsconfig#include entry. That silently breaks type declarations
// for side-effect CSS imports (e.g. `import "../global.css"`), which live in expo/types.
// This file survives NativeWind's rewrite (it's kept in tsconfig#include), so the
// reference lives here instead of depending on expo-env.d.ts's fragile lifecycle.
